name: fontpreview
adopt-info: fontpreview
summary: fontpreview lets you quickly search for fonts and preview them
description: |
  fontpreview is a commandline tool that lets you quickly search for fonts that are installed on your machine and preview them.

grade: stable
confinement: strict
base: core18

license: MIT

architectures:
  - build-on: amd64

apps: 
  fontpreview:
    extensions: 
      - gnome-3-34
    command: fontpreview
    plugs:
      - home
      - x11
      - unity7
      - desktop-legacy
      - desktop
      - mount-observe
   
parts:
  fontpreview:
    source: https://github.com/sdushantha/fontpreview
    source-type: git
    plugin: make
    
    build-packages:
      - make
      - xdotool
      - imagemagick
      - sxiv
    
    stage-packages:
      - xdotool
      - sxiv  

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
  
  fzf:
    source: https://github.com/junegunn/fzf/releases/download/0.24.0/fzf-0.24.0-linux_amd64.tar.gz
    source-type: tar
    plugin: dump
 
  imagemagick:
    source: https://github.com/ImageMagick/ImageMagick
    source-type: git
    plugin: autotools
  
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - fzf
      - fontpreview
      - imagemagick
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done      
