name: fontpreview
adopt-info: fontpreview
summary: fontpreview lets you quickly search for fonts and preview them
description: |
  fontpreview is a commandline tool that lets you quickly search for fonts that are installed on your machine and preview them.
grade: stable
confinement: strict
base: core22

license: MIT

architectures:
  - build-on: amd64

apps: 
  fontpreview:
    extensions: 
      - gnome
    command: bin/fontpreview
    plugs:
      - home

parts:
  fontpreview:
    source: https://github.com/sdushantha/fontpreview
    source-type: git
    plugin: make
    
    build-packages:
      - make
      - xdotool
      - php-imagick
      - sxiv
      - fzf
    
    stage-packages:
      - xdotool
      - sxiv  
      - libimlib2
      - libxft2
      - libfreetype6
      - fontconfig
      - giflib-tools
      - libexif12
      - x11-xserver-utils
      - php-imagick
      - fzf

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
