name: fontpreview
version: git
summary: fontpreview lets you quickly search for fonts and preview them
description: |
  fontpreview is a commandline tool that lets you quickly search for fonts that are installed on your machine and preview them.
grade: stable
confinement: strict

apps: 
  fontpreview:
    command: fontpreview
    plugs:
      - home
      - system-files
      - x11
      - wayland
      - unity7
      - desktop-legacy
      - desktop
      - unity8
   
parts:
  fontpreview:
    source: https://github.com/sdushantha/fontpreview
    source-type: git
    plugin: make
    
    build-packages:
      - make
      - xdotool
      - imagemagick
      - sxiv
    
    stage-packages:
      - xdotool
      - imagemagick
      - sxiv   
