name: fontpreview
version: git
summary: fontpreview lets you quickly search for fonts and preview them
description: |
  fontpreview is a commandline tool that lets you quickly search for fonts that are installed on your machine and preview them.
grade: devel
confinement: devmode

base: core19

layout:
  /usr/bin/fontpreview:
    bind: $SNAP/usr/bin/fontpreview

apps: 
  fontpreview:
    command: $SNAP/usr/bin/fontpreview
    plugs:
      - home
#      - system-files
      - x11
      - unity7
      - desktop-legacy
      - desktop
#      - unity8
   
parts:
  fontpreview:
    source: https://github.com/sdushantha/fontpreview
    source-type: git
    plugin: autotools
    
    build-packages:
      - make
      - xdotool
      - imagemagick
      - sxiv
      - fzf
    
    stage-packages:
      - xdotool
      - imagemagick
      - sxiv   
      - fzf
